Repository AY2223S2-CS2113-T13-4/tp, pull requests merged in 2023-04, with the labels that each got.

#205 Fixed bug for event and lessons clash
  src/main/java/seedu/apollo/command/task/AddCommand.java
Labels: type.Bug, priority.High

#207 Fix Bug where program crashes when trying to delete lesson from module with no lessons added
  .gitignore
  src/main/java/seedu/apollo/command/module/DeleteModuleCommand.java
Labels: type.Bug, priority.High, severity.High

#210 Create new error message for invalid date
  src/main/java/seedu/apollo/command/task/AddCommand.java
  src/main/java/seedu/apollo/task/Deadline.java
  src/main/java/seedu/apollo/ui/Ui.java
Labels: type.Bug

#211 Fixed ShowMod bug where double print message occurs
  src/main/java/seedu/apollo/command/module/ShowModuleCommand.java
Labels: type.Bug, priority.Medium, severity.Low

#215 Add alert for duplicate module in moduleData.txt
  src/main/java/seedu/apollo/exception/utils/DuplicateModuleInTextFileException.java
  src/main/java/seedu/apollo/storage/Storage.java
  src/main/java/seedu/apollo/ui/Ui.java
Labels: type.Bug, priority.High

#216 Update week command to show class number
  src/main/java/seedu/apollo/ui/Ui.java
Labels: type.Enhancement, priority.Low

#222 Improve code quality based on Code Review comments
  src/main/java/seedu/apollo/command/module/AddModuleCommand.java
  src/main/java/seedu/apollo/command/task/AddCommand.java
Labels: type.Task, priority.Low

#228 Update PPP
  docs/team/irving.md
Labels: type.Task

#227 Branch enhancement
  docs/team/aatmika.md
  src/main/java/seedu/apollo/command/task/AddCommand.java
  src/main/java/seedu/apollo/command/utils/DateHelpCommand.java
  src/main/java/seedu/apollo/command/utils/DeadlineHelpCommand.java
  src/main/java/seedu/apollo/command/utils/DeleteHelpCommand.java
  src/main/java/seedu/apollo/command/utils/EventHelpCommand.java
  src/main/java/seedu/apollo/command/utils/FindHelpCommand.java
  src/main/java/seedu/apollo/command/utils/HelpCommand.java
  src/main/java/seedu/apollo/command/utils/ListHelpCommand.java
  src/main/java/seedu/apollo/command/utils/MarkHelpCommand.java
  src/main/java/seedu/apollo/command/utils/TodoHelpCommand.java
  src/main/java/seedu/apollo/command/utils/UnmarkHelpCommand.java
  src/main/java/seedu/apollo/ui/Parser.java
  src/main/java/seedu/apollo/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement

#233 Add ListModuleWithLesson Command
  src/main/java/seedu/apollo/command/module/ListModuleWithLessonCommand.java
  src/main/java/seedu/apollo/exception/module/LessonNotAddedException.java
  src/main/java/seedu/apollo/exception/module/LessonTypeNotAddedException.java
  src/main/java/seedu/apollo/ui/Parser.java
  src/main/java/seedu/apollo/ui/Ui.java
Labels: type.Enhancement, priority.Medium

#244 Branch j unit tests
  docs/team/PoobalanAatmikaLakshmi.md
  docs/uml-diagrams/DateCommand-DateCommand__Find_tasks_by_date_.png
  docs/uml-diagrams/FindCommand-FindCommand__Find_tasks_.png
  docs/uml-source/DateCommand.puml
  docs/uml-source/FindCommand.puml
  src/test/java/seedu/apollo/ParserTest.java
  src/test/java/seedu/apollo/command/task/SpecificHelpCommandTest.java
Labels: type.Test

#245 Add week enhancement
  src/main/java/seedu/apollo/module/Timetable.java
  src/main/java/seedu/apollo/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement

#255 Change DateTime format
  docs/UserGuide.md
  src/main/java/seedu/apollo/command/task/DateCommand.java
  src/main/java/seedu/apollo/task/Deadline.java
  src/main/java/seedu/apollo/task/Event.java
  src/main/java/seedu/apollo/task/Task.java
  src/main/java/seedu/apollo/ui/Ui.java
  src/test/java/seedu/apollo/ParserTest.java
  src/test/java/seedu/apollo/command/task/AddCommandTest.java
  src/test/java/seedu/apollo/command/task/DateCommandTest.java
  src/test/java/seedu/apollo/task/DeadlineTest.java
  src/test/java/seedu/apollo/task/EventTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Enhancement

#257 Update UG and Ui to display Week Number of semester when printing timetable
  docs/UserGuide.md
  src/main/java/seedu/apollo/ui/Ui.java
Labels: type.Enhancement, priority.Medium

#315 Update logger field to fix logger bug
  src/main/java/seedu/apollo/command/Command.java
  src/main/java/seedu/apollo/utils/LoggerInterface.java
Labels: type.Bug, priority.High, severity.High
