Repository AY2223S2-CS2113-T13-4/tp, pull requests merged in 2023-03, with the labels that each got.

#18 Created Module base class
  src/main/java/seedu/apollo/module/Module.java
Labels: type.Story, priority.High

#22 ModuleList Class
  src/main/java/seedu/apollo/Ui.java
  src/main/java/seedu/apollo/command/ListModuleCommand.java
  src/main/java/seedu/apollo/module/ModuleList.java
Labels: type.Story, priority.High

#23 Add Junit testing for listCommand on empty list
  .gitignore
  src/test/java/seedu/apollo/UiTest.java
Labels: type.Task, priority.High

#28 Add del Mod functionality
  src/main/java/seedu/apollo/Ui.java
  src/main/java/seedu/apollo/command/DeleteModuleCommand.java
  src/main/java/seedu/apollo/module/Module.java
  src/main/java/seedu/apollo/module/ModuleList.java
Labels: type.Story, priority.High

#33 Integrate NUSMods Data for backend
  build.gradle
  data/data.json
  src/main/java/seedu/apollo/Apollo.java
  src/main/java/seedu/apollo/Parser.java
  src/main/java/seedu/apollo/Storage.java
  src/main/java/seedu/apollo/Ui.java
  src/main/java/seedu/apollo/command/AddCommand.java
  src/main/java/seedu/apollo/command/AddModuleCommand.java
  src/main/java/seedu/apollo/command/Command.java
  src/main/java/seedu/apollo/command/DateCommand.java
  src/main/java/seedu/apollo/command/ExitCommand.java
  src/main/java/seedu/apollo/command/FindCommand.java
  src/main/java/seedu/apollo/command/HelpCommand.java
  src/main/java/seedu/apollo/command/ListCommand.java
  src/main/java/seedu/apollo/command/ListModuleCommand.java
  src/main/java/seedu/apollo/command/ModifyCommand.java
  src/main/java/seedu/apollo/exception/InvalidModule.java
  src/main/java/seedu/apollo/module/Module.java
  src/main/java/seedu/apollo/module/ModuleList.java
  src/main/java/seedu/apollo/module/Timetable.java
  src/test/java/seedu/apollo/ParserTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Story, priority.High

#40 Add Exception Handling for addmod and delmod commands
  src/main/java/seedu/apollo/Parser.java
  src/main/java/seedu/apollo/Ui.java
  src/main/java/seedu/apollo/command/AddModuleCommand.java
  src/main/java/seedu/apollo/exception/EmptyAddModException.java
  src/main/java/seedu/apollo/exception/EmptyDelModException.java
Labels: type.Bug, severity.High

#41 Update find method for ModuleList
  src/main/java/seedu/apollo/Parser.java
  src/main/java/seedu/apollo/command/AddModuleCommand.java
  src/main/java/seedu/apollo/command/DeleteModuleCommand.java
  src/main/java/seedu/apollo/module/ModuleList.java
  src/test/java/seedu/apollo/module/ModuleListTest.java
Labels: type.Task, priority.Low

#45 Added Functionality of saving ModuleList to hard drive
  .gitignore
  src/main/java/seedu/apollo/Apollo.java
  src/main/java/seedu/apollo/Storage.java
  src/main/java/seedu/apollo/command/AddCommand.java
  src/main/java/seedu/apollo/command/AddModuleCommand.java
  src/main/java/seedu/apollo/command/DeleteModuleCommand.java
  src/main/java/seedu/apollo/command/ModifyCommand.java
  src/test/java/seedu/apollo/UiTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Story, type.Enhancement, priority.High

#47 Update JUnit tests to fix build gradle error
  src/test/java/seedu/apollo/UiTest.java
Labels: type.Bug, priority.High, severity.High

#48 Store data.json in resource folder
  build.gradle
  src/main/java/seedu/apollo/Apollo.java
  src/main/java/seedu/apollo/Storage.java
  src/main/resources/data.json
  src/test/java/seedu/apollo/UiTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task, priority.High

#49 Refactor packages for better organisation
  src/main/java/seedu/apollo/Apollo.java
  src/main/java/seedu/apollo/command/Command.java
  src/main/java/seedu/apollo/command/module/AddModuleCommand.java
  src/main/java/seedu/apollo/command/module/DeleteModuleCommand.java
  src/main/java/seedu/apollo/command/module/ListModuleCommand.java
  src/main/java/seedu/apollo/command/task/AddCommand.java
  src/main/java/seedu/apollo/command/task/DateCommand.java
  src/main/java/seedu/apollo/command/task/FindCommand.java
  src/main/java/seedu/apollo/command/task/ListCommand.java
  src/main/java/seedu/apollo/command/task/ModifyCommand.java
  src/main/java/seedu/apollo/command/utils/ExitCommand.java
  src/main/java/seedu/apollo/command/utils/HelpCommand.java
  src/main/java/seedu/apollo/exception/module/EmptyAddModException.java
  src/main/java/seedu/apollo/exception/module/EmptyDelModException.java
  src/main/java/seedu/apollo/exception/module/InvalidModule.java
  src/main/java/seedu/apollo/exception/module/ModuleNotFoundException.java
  src/main/java/seedu/apollo/exception/task/DateOrderException.java
  src/main/java/seedu/apollo/exception/task/EmptyTaskDescException.java
  src/main/java/seedu/apollo/exception/task/InvalidDateTime.java
  src/main/java/seedu/apollo/exception/task/InvalidDeadline.java
  src/main/java/seedu/apollo/exception/task/InvalidEvent.java
  src/main/java/seedu/apollo/exception/utils/EmptyKeywordException.java
  src/main/java/seedu/apollo/exception/utils/IllegalCommandException.java
  src/main/java/seedu/apollo/exception/utils/InvalidSaveFile.java
  src/main/java/seedu/apollo/module/ModuleList.java
  src/main/java/seedu/apollo/storage/Storage.java
  src/main/java/seedu/apollo/task/Deadline.java
  src/main/java/seedu/apollo/task/Event.java
  src/main/java/seedu/apollo/ui/Parser.java
  src/main/java/seedu/apollo/ui/Ui.java
  src/test/java/seedu/apollo/ParserTest.java
  src/test/java/seedu/apollo/UiTest.java
Labels: type.Task, priority.Medium

#51 Update help command
  src/main/java/seedu/apollo/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium, severity.Low

#53 Add additional JUnit test for ModuleList
  src/test/java/seedu/apollo/module/ModuleListTest.java
Labels: priority.Medium, type.Test

#59 Update Storage class to setup logger
  .gitignore
  src/main/java/seedu/apollo/storage/Storage.java
Labels: type.Task, priority.Medium

#67 Add assertions for module commands
  src/main/java/seedu/apollo/command/module/AddModuleCommand.java
  src/main/java/seedu/apollo/command/module/ListModuleCommand.java
Labels: type.Task, priority.Medium

#69 Update datetime formatter to fix formatting bug
  src/main/java/seedu/apollo/task/Task.java
  src/main/java/seedu/apollo/ui/Ui.java
  src/test/java/seedu/apollo/ParserTest.java
Labels: type.Bug, severity.Low

#80 Fix event bug
  src/main/java/seedu/apollo/ui/Parser.java
Labels: type.Bug, priority.Medium, severity.Medium

#83 Add Exception for AddModuleCommand
  src/main/java/seedu/apollo/command/module/AddModuleCommand.java
  src/main/java/seedu/apollo/exception/module/DuplicateModuleException.java
  src/main/java/seedu/apollo/ui/Ui.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, severity.Medium

#85 Update findTasks methods to use streams
  src/main/java/seedu/apollo/task/TaskList.java
  src/main/java/seedu/apollo/ui/Ui.java
Labels: type.Task, priority.Low

#90 Add total task count and number of unmarked tasks
  src/main/java/seedu/apollo/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: type.Story, type.Enhancement, priority.High

#91 User guide v2.0
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#95 Add mod enhancements
  src/main/java/seedu/apollo/Apollo.java
  src/main/java/seedu/apollo/command/Command.java
  src/main/java/seedu/apollo/command/module/AddModuleCommand.java
  src/main/java/seedu/apollo/command/module/DeleteModuleCommand.java
  src/main/java/seedu/apollo/command/module/ListModuleCommand.java
  src/main/java/seedu/apollo/command/task/AddCommand.java
  src/main/java/seedu/apollo/command/task/DateCommand.java
  src/main/java/seedu/apollo/command/task/FindCommand.java
  src/main/java/seedu/apollo/command/task/ListCommand.java
  src/main/java/seedu/apollo/command/task/ModifyCommand.java
  src/main/java/seedu/apollo/command/utils/ExitCommand.java
  src/main/java/seedu/apollo/command/utils/HelpCommand.java
  src/main/java/seedu/apollo/exception/module/ClassNotFoundException.java
  src/main/java/seedu/apollo/module/LessonType.java
  src/main/java/seedu/apollo/module/Module.java
  src/main/java/seedu/apollo/module/Timetable.java
  src/main/java/seedu/apollo/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement, type.Task, priority.High

#94 Update Developer Guide #87
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#96 Add checking for whether lesson type exists already for module
  src/main/java/seedu/apollo/command/module/AddModuleCommand.java
  src/main/java/seedu/apollo/exception/module/LessonAddedException.java
  src/main/java/seedu/apollo/module/Module.java
  src/main/java/seedu/apollo/ui/Ui.java
Labels: type.Enhancement, type.Task, priority.High

#102 Add documentation
  docs/DeveloperGuide.md
  src/main/java/seedu/apollo/command/module/DeleteModuleCommand.java
  src/main/java/seedu/apollo/module/Module.java
  src/main/java/seedu/apollo/module/Timetable.java
Labels: priority.High

#103 Get total MCs #79, Addmod enhancement user guide updates and update UG
  docs/UserGuide.md
  src/main/java/seedu/apollo/command/module/AddModuleCommand.java
  src/main/java/seedu/apollo/command/module/DeleteModuleCommand.java
  src/main/java/seedu/apollo/module/ModuleList.java
  src/main/java/seedu/apollo/ui/Ui.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Enhancement, priority.High

#104 AddMod enhancements
  src/main/java/seedu/apollo/command/module/AddModuleCommand.java
  src/main/java/seedu/apollo/module/Module.java
  src/main/java/seedu/apollo/storage/Storage.java
  src/main/java/seedu/apollo/utils/LessonTypeUtil.java
  src/main/java/seedu/apollo/utils/Logger.java
Labels: type.Enhancement, type.Task, priority.High

#106 Edit Ui
  src/main/java/seedu/apollo/ui/Ui.java
  src/test/java/seedu/apollo/ParserTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High

#107 Add dev notes for modify task commands
  docs/DeveloperGuide.md
Labels: type.Task

#112 Update README
  docs/README.md
Labels: type.Task

#122 Add calendar data structure
  src/main/java/seedu/apollo/Apollo.java
  src/main/java/seedu/apollo/calendar/Calendar.java
  src/main/java/seedu/apollo/command/Command.java
  src/main/java/seedu/apollo/command/module/AddModuleCommand.java
  src/main/java/seedu/apollo/command/module/DeleteModuleCommand.java
  src/main/java/seedu/apollo/command/module/ListModuleCommand.java
  src/main/java/seedu/apollo/command/task/AddCommand.java
  src/main/java/seedu/apollo/command/task/DateCommand.java
  src/main/java/seedu/apollo/command/task/FindCommand.java
  src/main/java/seedu/apollo/command/task/ListCommand.java
  src/main/java/seedu/apollo/command/task/ModifyCommand.java
  src/main/java/seedu/apollo/command/utils/ExitCommand.java
  src/main/java/seedu/apollo/command/utils/HelpCommand.java
  src/main/java/seedu/apollo/module/CalendarModule.java
  src/main/java/seedu/apollo/module/Module.java
  src/main/java/seedu/apollo/storage/Storage.java
Labels: type.Enhancement, type.Task, priority.High

#127 Add functionality to delete module lessons
  src/main/java/seedu/apollo/command/module/AddModuleCommand.java
  src/main/java/seedu/apollo/command/module/DeleteModuleCommand.java
  src/main/java/seedu/apollo/storage/Storage.java
  src/main/java/seedu/apollo/ui/Ui.java
  src/main/java/seedu/apollo/utils/LoggerInterface.java
Labels: type.Enhancement, type.Task, priority.High

#132 Enhance delmod to allow deletion of modules by index
  src/main/java/seedu/apollo/command/module/DeleteModuleCommand.java
  src/main/java/seedu/apollo/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement, priority.Medium

#137 Add chronological sorting for lessons in calendar
  src/main/java/seedu/apollo/calendar/Calendar.java
Labels: type.Enhancement, priority.Medium

#140 Add showmod command to display module information
  docs/UserGuide.md
  src/main/java/seedu/apollo/command/module/AddModuleCommand.java
  src/main/java/seedu/apollo/command/module/ListModuleCommand.java
  src/main/java/seedu/apollo/command/module/ShowModuleCommand.java
  src/main/java/seedu/apollo/command/task/AddCommand.java
  src/main/java/seedu/apollo/command/task/DateCommand.java
  src/main/java/seedu/apollo/command/task/FindCommand.java
  src/main/java/seedu/apollo/command/task/ListCommand.java
  src/main/java/seedu/apollo/command/task/ModifyCommand.java
  src/main/java/seedu/apollo/exception/module/EmptyShowModException.java
  src/main/java/seedu/apollo/module/Module.java
  src/main/java/seedu/apollo/ui/Parser.java
  src/main/java/seedu/apollo/ui/Ui.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Story, priority.High

#141 Add ability to show available lessons for a particular lesson type of a module
  src/main/java/seedu/apollo/command/Command.java
  src/main/java/seedu/apollo/command/module/AddModuleCommand.java
  src/main/java/seedu/apollo/command/module/DeleteModuleCommand.java
  src/main/java/seedu/apollo/command/module/ShowModuleCommand.java
  src/main/java/seedu/apollo/ui/Ui.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Enhancement, type.Task, priority.Medium

#145 Added warning message for when two lessons in timetable clash
  src/main/java/seedu/apollo/command/module/AddModuleCommand.java
  src/main/java/seedu/apollo/ui/Ui.java
  src/main/java/seedu/apollo/utils/DayTypeUtil.java
Labels: type.Enhancement, type.Task, priority.Medium

#148 Add 100% coverage for ListCommand
  src/test/java/seedu/apollo/command/task/ListCommandTest.java
Labels: type.Test

#151 Update UserGuide for showmod
  docs/UserGuide.md
Labels: type.Task

#152 Add 100% coverage for Module Commands
  .gitignore
  src/main/java/seedu/apollo/command/module/ListModuleCommand.java
  src/test/java/seedu/apollo/command/module/AddModuleCommandTest.java
  src/test/java/seedu/apollo/command/module/DeleteModuleCommandTest.java
  src/test/java/seedu/apollo/command/module/ListModuleCommandTest.java
  src/test/java/seedu/apollo/command/module/ShowModuleCommandTest.java
  src/test/java/seedu/apollo/command/task/ListCommandTest.java
Labels: type.Test

#153 Update help message to reflect latest commands
  src/main/java/seedu/apollo/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: type.Bug, severity.Low

#154 Add 100% coverage for WeekCommand
  src/test/java/seedu/apollo/command/WeekCommandTest.java
Labels: type.Test

#159 Update UserGuide
  docs/UserGuide.md
Labels: type.Task

#164 Add event module clash warning functionality
  src/main/java/seedu/apollo/command/task/AddCommand.java
  src/main/java/seedu/apollo/ui/Ui.java
  src/main/java/seedu/apollo/utils/DayTypeUtil.java
  src/main/java/seedu/apollo/utils/LessonTypeUtil.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement, priority.High

#173 Add 100% coverage for exception.module
  src/test/java/seedu/apollo/ParserTest.java
  src/test/java/seedu/apollo/command/module/AddModuleCommandTest.java
  src/test/java/seedu/apollo/command/module/DeleteModuleCommandTest.java
Labels: priority.High, type.Test
